# Generated by glean-deploy init --cloud gcp
# DO NOT EDIT THIS FILE MANUALLY — re-run glean-deploy init to regenerate.
#
# References:
#   Terraform input variables: https://developer.hashicorp.com/terraform/language/values/variables
#   GCP Terraform provider:    https://registry.terraform.io/providers/hashicorp/google/latest/docs

variable "project_id" {
  description = "GCP project ID. See https://cloud.google.com/resource-manager/docs/creating-managing-projects"
  type        = string
  default     = "<your-gcp-project-id>"
}

variable "region" {
  description = "GCP region. See https://cloud.google.com/compute/docs/regions-zones"
  type        = string
  default     = "us-central1"
}

variable "cluster_name" {
  description = "GKE cluster name. See https://cloud.google.com/kubernetes-engine/docs"
  type        = string
  default     = "<your-cluster-name>"
}

variable "namespace" {
  description = "Kubernetes namespace for the CronJob."
  type        = string
  default     = "default"
}

variable "image" {
  description = "Container image URI in Artifact Registry. See https://cloud.google.com/artifact-registry/docs"
  type        = string
  default     = "<region>-docker.pkg.dev/<project>/connectors/wikipedia_connector:latest"
}

variable "cluster_endpoint" {
  description = <<-EOT
    Override the GKE cluster API endpoint used by the Terraform kubernetes provider.
    Required for private-only GKE clusters (enablePublicEndpoint: false) that expose a GKE DNS
    endpoint (*.gke.goog). Set to the full DNS hostname, e.g. "abc123.gke.goog".
    Leave empty ("") to use the endpoint auto-discovered from the cluster data source.
    Reference: https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture#control_plane_endpoint_modes
  EOT
  type        = string
  default     = ""
}
