# Generated by glean-deploy init --cloud gcp
# DO NOT EDIT THIS FILE MANUALLY — re-run glean-deploy init to regenerate.
#
# References:
#   Terraform input variables: https://developer.hashicorp.com/terraform/language/values/variables
#   GCP Terraform provider:    https://registry.terraform.io/providers/hashicorp/google/latest/docs

variable "project_id" {
  description = "GCP project ID. See https://cloud.google.com/resource-manager/docs/creating-managing-projects"
  type        = string
  default     = "dev-sandbox-334901"
}

variable "region" {
  description = "GCP region. See https://cloud.google.com/compute/docs/regions-zones"
  type        = string
  default     = "us-central1-a"
}

variable "cluster_name" {
  description = "GKE cluster name. See https://cloud.google.com/kubernetes-engine/docs"
  type        = string
  default     = "glean-deploy"
}

variable "namespace" {
  description = "Kubernetes namespace for the CronJob."
  type        = string
  default     = "default"
}

variable "image" {
  description = "Container image URI in Artifact Registry. See https://cloud.google.com/artifact-registry/docs"
  type        = string
  default     = "us-central1-docker.pkg.dev/dev-sandbox-334901/glean-connectors/webex:latest"
}
